"""Adjusted some fields to be nullable in some models, added index on student profile name lookup.

Revision ID: 09081763d093
Revises: 61e7381d3b74
Create Date: 2026-04-18 12:22:28.508765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09081763d093'
down_revision: Union[str, Sequence[str], None] = '61e7381d3b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instructor_profile', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('student_profile', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('student_profile', 'address',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.create_index('ix_user_full_name', 'student_profile', ['first_name', 'last_name', 'middle_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_full_name', table_name='student_profile')
    op.alter_column('student_profile', 'address',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('student_profile', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('instructor_profile', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
